/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c SendFileAdaptor -p sendfileadaptor.h:sendfileadaptor.cpp ../../resources/dbus/eu.playview.renaudguezennec.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "sendfileadaptor.h"

/*
 * Implementation of interface class SendFileAdaptor
 */

SendFileAdaptor::SendFileAdaptor(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

SendFileAdaptor::~SendFileAdaptor()
{
}

