/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TableViewAdaptor -a tableviewadaptor.h:tableviewadaptor.cpp ../resources/dbus/eu.playview.renaudguezennec.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "tableviewadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TableViewAdaptor
 */

TableViewAdaptor::TableViewAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TableViewAdaptor::~TableViewAdaptor()
{
    // destructor
}

void TableViewAdaptor::OnForceWriting()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.OnForceWriting
    QMetaObject::invokeMethod(parent(), "OnForceWriting");
}

void TableViewAdaptor::OnRegex()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.OnRegex
    QMetaObject::invokeMethod(parent(), "OnRegex");
}

void TableViewAdaptor::OnSort()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.OnSort
    QMetaObject::invokeMethod(parent(), "OnSort");
}

void TableViewAdaptor::OnUpdate()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.OnUpdate
    QMetaObject::invokeMethod(parent(), "OnUpdate");
}

void TableViewAdaptor::PopupMenurequested(const QPoint &pos)
{
    // handle method call local.qdbuscpp2xml.PL_TableView.PopupMenurequested
    QMetaObject::invokeMethod(parent(), "PopupMenurequested", Q_ARG(QPoint, pos));
}

void TableViewAdaptor::cancel()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.cancel
    QMetaObject::invokeMethod(parent(), "cancel");
}

void TableViewAdaptor::copy()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.copy
    QMetaObject::invokeMethod(parent(), "copy");
}

void TableViewAdaptor::cut()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.cut
    QMetaObject::invokeMethod(parent(), "cut");
}

void TableViewAdaptor::onFileNameAsTitle()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onFileNameAsTitle
    QMetaObject::invokeMethod(parent(), "onFileNameAsTitle");
}

void TableViewAdaptor::onForce()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onForce
    QMetaObject::invokeMethod(parent(), "onForce");
}

void TableViewAdaptor::onModify()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onModify
    QMetaObject::invokeMethod(parent(), "onModify");
}

void TableViewAdaptor::onMoveSelection()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onMoveSelection
    QMetaObject::invokeMethod(parent(), "onMoveSelection");
}

void TableViewAdaptor::onRemove()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onRemove
    QMetaObject::invokeMethod(parent(), "onRemove");
}

void TableViewAdaptor::onSelect(int p)
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onSelect
    QMetaObject::invokeMethod(parent(), "onSelect", Q_ARG(int, p));
}

void TableViewAdaptor::onremoveFile()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.onremoveFile
    QMetaObject::invokeMethod(parent(), "onremoveFile");
}

void TableViewAdaptor::paste()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.paste
    QMetaObject::invokeMethod(parent(), "paste");
}

void TableViewAdaptor::sendFile()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.sendFile
    QMetaObject::invokeMethod(parent(), "sendFile");
}

void TableViewAdaptor::sendSelectedFileToDevice()
{
    // handle method call local.qdbuscpp2xml.PL_TableView.sendSelectedFileToDevice
    QMetaObject::invokeMethod(parent(), "sendSelectedFileToDevice");
}

